import { mkdirSync, writeFileSync } from "node:fs";

const outputs = [
  ".harness-cache/planning-inspection.json",
  "reports/planning-audit.md",
  "traces/planning-audit.trace"
];

if (process.argv.includes("--dry-run")) {
  console.log("planning audit would write:");
  for (const output of outputs) {
    console.log(output);
  }
  process.exit(0);
}

mkdirSync(".harness-cache", { recursive: true });
mkdirSync("reports", { recursive: true });
mkdirSync("traces", { recursive: true });

for (const output of outputs) {
  writeFileSync(output, `generated by planning audit: ${output}\n`);
}

console.log("planning audit wrote generated project artifacts");
