from __future__ import annotations

import contextlib
import os
from pathlib import Path
from typing import List

from agent_loom.compound.blocks import (
    upsert_managed_block,
    upsert_managed_block_preserving_non_placeholder,
)
from agent_loom.compound.instincts import (
    InstinctStore,
    load_instincts,
    render_instincts_index,
)
from agent_loom.compound.scaffold import require_scaffold_installed


def _normalize_newlines(text: str) -> str:
    return str(text or "").replace("\r\n", "\n")


def _read_text(p: Path, fallback: str = "") -> str:
    try:
        return p.read_text(encoding="utf-8")
    except Exception:
        return fallback


def _write_text(p: Path, text: str) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(_normalize_newlines(text).rstrip() + "\n", encoding="utf-8")


@contextlib.contextmanager
def _chdir(p: Path):
    prev = Path.cwd()
    os.chdir(p)
    try:
        yield
    finally:
        os.chdir(prev)


def render_agents_ai_behavior() -> str:
    # Keep this small and stable; it is always-on.
    return _normalize_newlines(
        """# Compound Engineering Baseline

This block is maintained by the compound system.

**Core loop:** Plan -> Work -> Review -> Compound -> Repeat.

**Memory model:**
- **Observations** are logged automatically from tool calls and session events.
- **Instincts** are small heuristics extracted from observations.
- **Skills** are durable procedural memory (directory + SKILL.md) and are the primary compounding mechanism.
- **Episodes** are immutable evidence capsules. If a patch is too large to inline, the full patch is stored as a blob.
- **Decisions** are append-only records of normalized ops applied to instincts/skills (governance; replayable).

**Non-negotiables:**
- Keep skills small, specific, and triggerable from the `description`.
- Prefer updating an existing skill over creating a near-duplicate.
- Never put secrets into skills, memos, or observations.

**Where things live:**
- Skills: `.opencode/skills/<name>/SKILL.md`
- Instincts: `.loom/compound/instincts.json` (index at `.loom/compound/INSTINCTS.md`)
- Observations: `.opencode/memory/observations.jsonl` (gitignored by default)
- Episodes: `.loom/compound/episodes/YYYY/MM/<episode_id>.json` (committed evidence)
- Blobs: `.loom/compound/blobs/<sha256>.<ext>` (full patches, raw proposals, prompt snapshots)
- Decisions: `.loom/compound/decisions/YYYY/MM/<decision_id>.json` (append-only ops log)

**Core docs:**
- `AGENTS.md` (stable human-owned overview)
- `LOOM.md` (derived always-on context + instincts summary)
- `.loom/compound/ROADMAP.md` (direction + backlog + changelog)
"""
    )


def render_workflow_commands() -> str:
    return _normalize_newlines(
        """- `/workflow-plan` - Create tickets + plan (uses `loom memory recall`)
- `/workflow-work` - Work in a worktree and implement
- `/workflow-review` - Review changes before merge
- `/workflow-compound` - Capture durable learnings (memos + skills)
"""
    )


def render_loom_core_context() -> str:
    return _normalize_newlines(
        """# Loom always-on context (second-order compression)

This block is intentionally *small and stable*. Only update it when a principle has proven durable.

- First-order: observations -> instincts -> skills.
- Second-order: compress patterns into a few fundamentals that are always-on.
- Prefer agent-native primitives: ticket, memory, workspace, team.
- Governance loop: Plan -> Work -> Review -> Compound -> Repeat.

@.loom/compound/ROADMAP.md
"""
    )


def scan_rules(root: Path) -> List[str]:
    rules_dir = root / ".opencode" / "rules"
    if not rules_dir.exists() or not rules_dir.is_dir():
        return []
    out: List[str] = []
    for p in sorted(rules_dir.glob("*.md")):
        out.append(p.name)
    return out


def render_rules_index(root: Path) -> str:
    rules = scan_rules(root)
    if not rules:
        return "- _(none)_"
    return "\n".join([f"- {name}: .opencode/rules/{name}" for name in rules])


def sync_instincts_markdown(*, root: Path, store: InstinctStore) -> None:
    md_path = root / ".loom" / "compound" / "INSTINCTS.md"
    existing = _read_text(
        md_path,
        fallback=_normalize_newlines(
            """# INSTINCTS

<!-- BEGIN:compound:instincts-md -->
(autogenerated)
<!-- END:compound:instincts-md -->
"""
        ),
    )
    inner = "\n".join(
        [
            "## Active instincts (top confidence)",
            "",
            render_instincts_index(store.instincts, max_items=40),
            "",
            "## Notes",
            "",
            "- Instincts are the pre-skill layer: small, repeatable heuristics.",
            "- When an instinct proves useful across sessions, promote it into a Skill.",
        ]
    )
    updated = upsert_managed_block(existing, "instincts-md", inner)
    _write_text(md_path, updated)


def sync_docs(*, root: Path) -> None:
    require_scaffold_installed(root)

    instincts = load_instincts(root / ".loom" / "compound" / "instincts.json")

    # LOOM.md (derived, AI-managed)
    ctx_path = root / "LOOM.md"
    ctx = _read_text(ctx_path, fallback="# LOOM\n")
    ctx = upsert_managed_block(ctx, "agents-ai-behavior", render_agents_ai_behavior())
    ctx = upsert_managed_block(ctx, "workflow-commands", render_workflow_commands())
    ctx = upsert_managed_block_preserving_non_placeholder(
        ctx, "loom-core-context", render_loom_core_context()
    )
    # Keep this small to reduce churn; the full index lives at .loom/compound/INSTINCTS.md.
    ctx = upsert_managed_block(
        ctx,
        "instincts-index",
        render_instincts_index(instincts.instincts, max_items=12),
    )
    ctx = upsert_managed_block(ctx, "rules-index", render_rules_index(root))
    _write_text(ctx_path, ctx)

    # ROADMAP.md
    roadmap_path = root / ".loom" / "compound" / "ROADMAP.md"
    roadmap = _read_text(roadmap_path)

    from agent_loom.compound.roadmap import (
        default_roadmap_compass,
        render_roadmap_backlog,
    )

    with _chdir(root):
        backlog = render_roadmap_backlog()
    roadmap = upsert_managed_block(roadmap, "roadmap-backlog", backlog)
    roadmap = upsert_managed_block_preserving_non_placeholder(
        roadmap, "roadmap-ai-notes", default_roadmap_compass()
    )
    _write_text(roadmap_path, roadmap)

    # INSTINCTS.md (derived)
    sync_instincts_markdown(root=root, store=instincts)
