from __future__ import annotations

import contextlib
import shutil
from importlib import resources
from pathlib import Path

from agent_loom.compound.models import CompoundInstallResult


def _template_root() -> Path:
    traversable = resources.files("agent_loom.compound").joinpath("opencode")
    with resources.as_file(traversable) as p:
        return Path(p)


def _is_file(p: Path) -> bool:
    with contextlib.suppress(OSError):
        return p.is_file()
    return False


def _copy_file(*, src: Path, dest: Path, overwrite: bool, dry_run: bool) -> str:
    if dest.exists() and not overwrite:
        return "skipped"

    if dry_run:
        return "wrote"

    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dest)
    return "wrote"


def _read_text_if_exists(p: Path) -> str:
    with contextlib.suppress(OSError):
        return p.read_text(encoding="utf-8")
    return ""


def _ensure_lines_in_file(
    *, dest: Path, required_lines: list[str], dry_run: bool
) -> str:
    existing = _read_text_if_exists(dest)
    existing_lines = [ln.rstrip("\n") for ln in existing.splitlines()]

    want: list[str] = []
    for ln in required_lines:
        s = ln.rstrip("\n")
        if not s:
            continue
        if s not in existing_lines:
            want.append(s)

    if not existing and not want:
        return "skipped"
    if existing and not want:
        return "skipped"

    next_text = existing.rstrip() + (
        "\n" if existing and not existing.endswith("\n") else ""
    )
    if not existing:
        next_text = ""
    next_text += "\n".join(want) + "\n"

    if dry_run:
        return "wrote"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(next_text, encoding="utf-8")
    return "wrote"


def _rel_posix(p: Path) -> str:
    return p.as_posix()


def _is_scaffold_file(rel: str) -> bool:
    # Files safe to overwrite with --force.
    return rel.startswith(
        (
            ".opencode/plugins/",
            ".opencode/commands/",
            ".opencode/agents/",
            ".opencode/compound/prompts/",
        )
    )


def _is_persistent_memory_file(rel: str) -> bool:
    return rel in (
        ".opencode/memory/instincts.json",
        ".opencode/memory/INSTINCTS.md",
    )


def _is_skill_file(rel: str) -> bool:
    return rel.startswith(".opencode/skills/")


def _ensure_compound_fences(text: str) -> tuple[str, bool]:
    # Must match the markers used by the OpenCode plugin.
    required = [
        "agents-ai-behavior",
        "workflow-commands",
        "loom-core-context",
        "instincts-index",
        "rules-index",
    ]

    missing: list[str] = []
    for ident in required:
        begin = f"<!-- BEGIN:compound:{ident} -->"
        end = f"<!-- END:compound:{ident} -->"
        if begin not in text or end not in text:
            missing.append(ident)

    if not missing:
        return text, False

    blocks: list[str] = []
    for ident in missing:
        blocks.append(
            "\n".join(
                [
                    f"<!-- BEGIN:compound:{ident} -->",
                    "(autogenerated)",
                    f"<!-- END:compound:{ident} -->",
                ]
            )
        )

    section = "\n".join(
        [
            "## Compound (OpenCode)",
            "",
            "These blocks are maintained by the Loom compound OpenCode plugin.",
            "Do not edit inside the BEGIN/END fences.",
            "",
            "\n\n".join(blocks),
            "",
        ]
    )

    return text.rstrip() + "\n\n" + section, True


def _ensure_doc_fences(text: str, *, ids: list[str]) -> tuple[str, bool]:
    changed = False
    out = text
    for ident in ids:
        begin = f"<!-- BEGIN:compound:{ident} -->"
        end = f"<!-- END:compound:{ident} -->"
        if begin in out and end in out:
            continue
        changed = True
        out = (
            out.rstrip()
            + "\n\n"
            + "\n".join([begin, "(autogenerated)", end, ""])  # trailing newline
        )
    return out, changed


def install_opencode(
    *, dest: Path, dry_run: bool, force: bool = False
) -> CompoundInstallResult:
    dest = dest.resolve()
    src = _template_root()

    wrote: list[str] = []
    skipped: list[str] = []
    warnings: list[str] = []

    # 1) Merge .opencode/
    # Default is non-destructive: scaffold files are created if missing; learned state is preserved.
    # Use force=True to refresh scaffold files only.
    src_opencode = src / ".opencode"
    if not src_opencode.exists() or not src_opencode.is_dir():
        raise FileNotFoundError(f"Template missing .opencode/: {src_opencode}")

    for p in sorted(src_opencode.rglob("*")):
        if p.is_dir():
            continue
        rel = p.relative_to(src)
        rel_str = _rel_posix(rel)
        dst = dest / rel

        # Never overwrite persistent state.
        if _is_persistent_memory_file(rel_str) or _is_skill_file(rel_str):
            if dst.exists():
                skipped.append(rel_str)
                continue
            status = _copy_file(src=p, dest=dst, overwrite=False, dry_run=dry_run)
            (wrote if status == "wrote" else skipped).append(rel_str)
            continue

        # Merge-required ignore rules (safe and idempotent).
        if rel_str == ".opencode/memory/.gitignore":
            status = _ensure_lines_in_file(
                dest=dst,
                required_lines=[
                    "observations.jsonl",
                    "observations.jsonl.*.bak",
                    "autolearn_failures/",
                ],
                dry_run=dry_run,
            )
            (wrote if status == "wrote" else skipped).append(rel_str)
            continue

        if rel_str == ".opencode/compound/.gitignore":
            status = _ensure_lines_in_file(
                dest=dst,
                required_lines=[
                    "state.json",
                    "*.tmp.*",
                ],
                dry_run=dry_run,
            )
            (wrote if status == "wrote" else skipped).append(rel_str)
            continue

        # Scaffold files: overwrite only with --force.
        overwrite = bool(force and _is_scaffold_file(rel_str))
        if dst.exists() and not overwrite:
            src_text = _read_text_if_exists(p)
            dst_text = _read_text_if_exists(dst)
            if (
                src_text
                and dst_text
                and src_text != dst_text
                and _is_scaffold_file(rel_str)
            ):
                warnings.append(
                    f"left existing {rel_str} (differs from template; re-run with --force to refresh scaffold files)"
                )
            skipped.append(rel_str)
            continue

        status = _copy_file(src=p, dest=dst, overwrite=overwrite, dry_run=dry_run)
        (wrote if status == "wrote" else skipped).append(rel_str)

    # 2) Loom-scoped root docs
    doc_specs: list[tuple[str, list[str]]] = [
        (
            "LOOM_ROADMAP.md",
            ["roadmap-backlog", "roadmap-ai-notes", "changelog-entries"],
        ),
    ]
    for name, required_ids in doc_specs:
        src_doc = src / name
        if not _is_file(src_doc):
            raise FileNotFoundError(f"Template missing {name}: {src_doc}")

        dst_doc = dest / name

        if not dst_doc.exists():
            status = _copy_file(
                src=src_doc, dest=dst_doc, overwrite=False, dry_run=dry_run
            )
            (wrote if status == "wrote" else skipped).append(name)
            continue

        raw = dst_doc.read_text(encoding="utf-8")
        new, changed = _ensure_doc_fences(raw, ids=required_ids)
        if not changed:
            skipped.append(name)
            continue

        if dry_run:
            wrote.append(name)
        else:
            dst_doc.write_text(new, encoding="utf-8")
            wrote.append(name)

    # 3) Patch AGENTS.md (never overwrite)
    agents = dest / "AGENTS.md"
    raw_agents = agents.read_text(encoding="utf-8") if agents.exists() else "# AGENTS\n"
    new_agents, changed = _ensure_compound_fences(raw_agents)
    if changed:
        if dry_run:
            wrote.append("AGENTS.md")
        else:
            agents.write_text(new_agents, encoding="utf-8")
            wrote.append("AGENTS.md")
    else:
        skipped.append("AGENTS.md")

    return CompoundInstallResult(
        dest=str(dest),
        dry_run=bool(dry_run),
        wrote=sorted(set(wrote)),
        skipped=sorted(set(skipped)),
        warnings=sorted(set(warnings)),
    )


__all__ = [
    "install_opencode",
]
