from __future__ import annotations

from pathlib import Path

SUBSYSTEM_NAME = "agent-loom-team"
SUBSYSTEM_VERSION = "1.3.0"

DEFAULT_TMUX_SESSION_PREFIX = "team"
DEFAULT_MANAGER_WINDOW = "manager"
DEFAULT_RUNS_DIR = Path(".team") / "runs"
DEFAULT_WORKTREES_DIRNAME = "worktrees"

DEFAULT_MANAGER_AGENT = "loom-team-manager"
DEFAULT_WORKER_AGENT = "loom-team-worker"
DEFAULT_INVESTIGATOR_AGENT = "loom-team-investigator"
DEFAULT_INTEGRATOR_AGENT = "loom-team-integrator"

DEFAULT_HARNESS = "opencode"  # or "claude"

DEFAULT_OBJECTIVE_NUDGE_S = 1800.0  # 30m
DEFAULT_DONE_CHECK_S = 900.0  # 15m
DEFAULT_DISBAND_REMINDER_RESEND_S = 21600.0  # 6h

# Worker idle detection: screen unchanged across captures.
DEFAULT_IDLE_SCREEN_S = 1800.0  # 30m

DEFAULT_AUTOCAPTURE_MIN_S = 600.0  # 10m
DEFAULT_AUTOCAPTURE_MAX_S = 900.0  # 15m
DEFAULT_AUTOCAPTURE_LINES = 200

TMUX_OPT_OWNED = "@team"
TMUX_OPT_TEAM = "@team_name"
TMUX_OPT_RUN_ID = "@team_run_id"
TMUX_OPT_RUN_DIR = "@team_run_dir"
TMUX_OPT_REPO_ROOT = "@team_repo_root"
TMUX_OPT_ROLE = "@team_role"
TMUX_OPT_WORKER_ID = "@team_worker_id"
TMUX_OPT_TICKET_ID = "@team_ticket_id"

ROLE_MANAGER = "manager"
ROLE_WORKER = "worker"
ROLE_INVESTIGATOR = "investigator"
ROLE_INTEGRATOR = "integrator"

INBOX_KIND_CONTROL = "control"
CONTROL_OP_BOUNCE = "bounce"

ENV_TEAM_NAME = "TEAM_NAME"
ENV_TEAM_RUN_ID = "TEAM_RUN_ID"
ENV_TEAM_RUN_DIR = "TEAM_RUN_DIR"
ENV_TEAM_ROLE = "TEAM_ROLE"
ENV_TEAM_WORKER_ID = "TEAM_WORKER_ID"
ENV_TEAM_TICKET_ID = "TEAM_TICKET_ID"
ENV_TEAM_SPRINT_NAME = "TEAM_SPRINT_NAME"
ENV_TEAM_SPRINT_TAG = "TEAM_SPRINT_TAG"

ENV_TICKET_DIR = "TICKET_DIR"
CANONICAL_TICKET_DIRNAME = ".tickets"

__all__ = [
    "SUBSYSTEM_NAME",
    "SUBSYSTEM_VERSION",
    "CANONICAL_TICKET_DIRNAME",
    "DEFAULT_AUTOCAPTURE_LINES",
    "DEFAULT_AUTOCAPTURE_MAX_S",
    "DEFAULT_AUTOCAPTURE_MIN_S",
    "DEFAULT_DISBAND_REMINDER_RESEND_S",
    "DEFAULT_DONE_CHECK_S",
    "DEFAULT_HARNESS",
    "DEFAULT_IDLE_SCREEN_S",
    "DEFAULT_INVESTIGATOR_AGENT",
    "DEFAULT_MANAGER_AGENT",
    "DEFAULT_MANAGER_WINDOW",
    "DEFAULT_INTEGRATOR_AGENT",
    "DEFAULT_OBJECTIVE_NUDGE_S",
    "DEFAULT_RUNS_DIR",
    "DEFAULT_TMUX_SESSION_PREFIX",
    "DEFAULT_WORKER_AGENT",
    "DEFAULT_WORKTREES_DIRNAME",
    "ENV_TEAM_NAME",
    "ENV_TEAM_ROLE",
    "ENV_TEAM_RUN_DIR",
    "ENV_TEAM_RUN_ID",
    "ENV_TEAM_SPRINT_NAME",
    "ENV_TEAM_SPRINT_TAG",
    "ENV_TEAM_TICKET_ID",
    "ENV_TEAM_WORKER_ID",
    "ENV_TICKET_DIR",
    "ROLE_INVESTIGATOR",
    "ROLE_INTEGRATOR",
    "ROLE_MANAGER",
    "ROLE_WORKER",
    "INBOX_KIND_CONTROL",
    "CONTROL_OP_BOUNCE",
    "TMUX_OPT_OWNED",
    "TMUX_OPT_REPO_ROOT",
    "TMUX_OPT_ROLE",
    "TMUX_OPT_RUN_DIR",
    "TMUX_OPT_RUN_ID",
    "TMUX_OPT_TEAM",
    "TMUX_OPT_TICKET_ID",
    "TMUX_OPT_WORKER_ID",
]
